trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - master
      - dev

name: SR-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  CHANGED_SERVICES: ''

stages:

# 1️⃣ Detect changes
- stage: Detect_Changes
  displayName: 'Detect Changes Stage'
  jobs:
  - job: Detect
    displayName: 'Detect Changed Services'
    steps:
    - checkout: self
    - script: |
        echo "Detecting changes for InventoryService..."
        git fetch origin master:refs/remotes/origin/master
        CHANGED=""
        if git diff --name-only HEAD origin/master | grep -q '^InventoryService/'; then
          CHANGED="InventoryService"
        fi
        echo "##vso[task.setvariable variable=CHANGED_SERVICES]$CHANGED"
      displayName: 'Detect Changed Services Script'

# 2️⃣ Build & Test
- stage: Build_Test
  displayName: 'Build & Test Stage'
  dependsOn: Detect_Changes
  condition: contains(variables['CHANGED_SERVICES'], 'InventoryService')
  jobs:
  - job: BuildInventory
    displayName: 'Build InventoryService'
    steps:
    - checkout: self
    - script: |
        echo "Building InventoryService..."
        cd InventoryService
        npm install
        echo "Running simple test..."
        node index.js
      displayName: 'Build and Run InventoryService'

# 3️⃣ Security Scan
- stage: Security_Scan
  displayName: 'Security Scan Stage'
  dependsOn: Build_Test
  condition: contains(variables['CHANGED_SERVICES'], 'InventoryService')
  jobs:
  - job: NodeScan
    displayName: 'Node.js Security Scan'
    steps:
    - checkout: self
    - script: |
        cd InventoryService
        npm install
        npm audit --audit-level=high
      displayName: 'Run npm audit'

# 4️⃣ Publish Artifact
- stage: Publish_Artifact
  displayName: 'Publish Artifact Stage'
  dependsOn: Security_Scan
  condition: contains(variables['CHANGED_SERVICES'], 'InventoryService')
  jobs:
  - job: Publish
    displayName: 'Publish InventoryService Artifact'
    steps:
    - checkout: self
    - publish: InventoryService
      artifact: InventoryService_$(Build.BuildId)
      displayName: 'Publish InventoryService'

