trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - master
      - dev

name: SR-$(Date:yyyyMMdd)$(Rev:.r)

variables:
  CHANGED_SERVICES: ''

stages:

# 1️⃣ Detect changes
- stage: Detect_Changes
  jobs:
  - job: Detect
    steps:
    - checkout: self
    - script: |
        echo "Detecting changes for InventoryService..."
        git fetch origin master:refs/remotes/origin/master
        CHANGED=""
        if git diff --name-only HEAD origin/master | grep -q '^InventoryService/'; then
          CHANGED="InventoryService"
        fi
        echo "##vso[task.setvariable variable=CHANGED_SERVICES]$CHANGED"
      displayName: 'Detect Changed Services'

# 2️⃣ Build & Test
- ${{ if contains(variables['CHANGED_SERVICES'], 'InventoryService') }}:
  - template: templates/build-template.yml
    parameters:
      serviceName: InventoryService
      path: InventoryService

# 3️⃣ Security Scan
- stage: Security_Scan
  condition: contains(variables['CHANGED_SERVICES'], 'InventoryService')
  jobs:
  - job: NodeScan
    steps:
    - script: |
        cd InventoryService
        npm audit --audit-level=high
      displayName: 'Node.js Security Scan'

# 4️⃣ Publish Artifact
- stage: Publish_Artifact
  condition: contains(variables['CHANGED_SERVICES'], 'InventoryService')
  jobs:
  - job: Publish
    steps:
    - publish: InventoryService
      artifact: InventoryService_$(Build.BuildId)

