trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - master
      - dev

name: SR-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest

stages:

# =============================
# 1️⃣ Detect Changes Stage
# =============================
- stage: Detect_Changes
  displayName: Detect Changes
  jobs:
  - job: Detect
    displayName: Detect Changed Services
    steps:
    - checkout: self
      fetchDepth: 0

    - script: |
        echo "Checking changes..."
        git log --oneline -2

        if git diff --name-only HEAD~1 HEAD | grep -q '^InventoryService/'; then
          echo "##vso[task.setvariable variable=InventoryChanged;isOutput=true]true"
        else
          echo "##vso[task.setvariable variable=InventoryChanged;isOutput=true]true"
        fi
      name: SetOutput

  
# =============================
# 2️⃣ Build Stage
# =============================
- stage: Build_Inventory
  displayName: Build InventoryService
  dependsOn: Detect_Changes
  condition: eq(dependencies.Detect_Changes.outputs['Detect.SetOutput.InventoryChanged'], 'true')
  jobs:
  - job: Build
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: |
        cd InventoryService
        npm install
        node index.js
      displayName: Install & Run

# =============================
# 3️⃣ Security Scan
# =============================
- stage: Security_Scan
  displayName: Security Scan
  dependsOn: Build_Inventory
  condition: eq(dependencies.Detect_Changes.outputs['Detect.SetOutput.InventoryChanged'], 'true')
  jobs:
  - job: Scan
    steps:
    - checkout: self
    - script: |
        cd InventoryService
        npm install
        npm audit --audit-level=high
      displayName: npm audit

# =============================
# 4️⃣ Publish Artifact
# =============================
- stage: Publish_Artifact
  displayName: Publish Artifact
  dependsOn: Security_Scan
  condition: eq(dependencies.Detect_Changes.outputs['Detect.SetOutput.InventoryChanged'], 'true')
  jobs:
  - job: Publish
    steps:
    - checkout: self
    - publish: InventoryService
      artifact: InventoryService_$(Build.BuildId)


